language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=spell
    - TOXENV=docs
    - TOXENV=2.7
    - TOXENV=2.7-nocover
    - TOXENV=3.4
    - TOXENV=3.4-nocover
    - TOXENV=pypy
    - TOXENV=pypy-nocover
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=2.7
    - env: TOXENV=2.7-nocover
    - env: TOXENV=3.4
    - env: TOXENV=3.4-nocover
    - env: TOXENV=pypy
    - env: TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

